name: OrangeFox - Custom Vendor Boot Builder

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: 🦊 Compile OrangeFox (Patched)
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python2 python3

      - name: Install Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo cp ~/bin/repo /usr/local/bin/repo

      - name: Initialize & Sync OrangeFox Manifest
        run: |
          mkdir ~/OrangeFox
          cd ~/OrangeFox
          git config --global user.name "Yash"
          git config --global user.email "bloxfruits_yash@example.com"
          repo init -u https://gitlab.com/OrangeFox/Manifest.git -b fox_12.1 --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Clone Device Tree
        run: |
          cd ~/OrangeFox
          git clone https://github.com/really-yash/twrp_device_xiaomi_air.git -b twrp-16.0 device/xiaomi/air

      - name: Patch mkbootimg for vendor_boot
        run: |
          cd ~/OrangeFox
          echo "Overwriting outdated mkbootimg to fix vendor_ramdisk_fragment errors..."
          wget https://raw.githubusercontent.com/aosp-mirror/platform_system_tools_mkbootimg/master/mkbootimg.py -O system/tools/mkbootimg/mkbootimg.py
          chmod +x system/tools/mkbootimg/mkbootimg.py

      - name: Compile OrangeFox
        run: |
          cd ~/OrangeFox
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export LC_ALL="C"
          lunch twrp_air-eng
          mka vendorbootimage

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-Recovery-Air
          path: |
            ~/OrangeFox/out/target/product/air/OrangeFox*.zip
            ~/OrangeFox/out/target/product/air/vendor_boot.img
